const _REQUESTED = '_REQUESTED';
const _FULFILLED = '_FULFILLED';
const _REJECTED = '_REJECTED';

export const LOGIN_REQUESTED = 'LOGIN' + _REQUESTED;
export const LOGIN_FULFILLED = 'LOGIN' + _FULFILLED;
export const LOGIN_REJECTED = 'LOGIN' + _REJECTED;

export const LOGOUT_REQUESTED = 'LOGOUT' + _REQUESTED;
export const LOGOUT_FULFILLED = 'LOGOUT' + _FULFILLED;
export const LOGOUT_REJECTED = 'LOGOUT' + _REJECTED;

export const SYNC_AUTH_STATE_REQUESTED = 'SYNC_AUTH_STATE' + _REQUESTED;
export const SYNC_AUTH_STATE_FULFILLED = 'SYNC_AUTH_STATE' + _FULFILLED;
export const SYNC_AUTH_STATE_REJECTED = 'SYNC_AUTH_STATE' + _REJECTED;

export const API_REQUESTED = 'API' + _REQUESTED;
export const API_FULFILLED = 'API' + _FULFILLED;
export const API_REJECTED = 'API' + _REJECTED;
